### ISSUE TITLE
App hangs directly after start

### ISSUE THREAD

**Issue by srsp** [holisticon/flynn-book-scanner#59]
When I start the app the "Loading" message appears and stays forever. See attached screenshot.

Environment:
Version 1.3.0 on Android 5.0.1, Nexus 6, english localization.

![screenshot_2015-01-30-16-37-25](https://cloud.githubusercontent.com/assets/1210541/5978274/f448f054-a89e-11e4-9bfa-6eb3cb242c60.png)

**Comment by hypery2k** [comment]
Did you update from an older version or just a fresh install?

**Comment by srsp** [comment]
Fresh install. Never tried Flynn before.

**Comment by hypery2k** [comment]
Fixed in release [1.3.1](https://github.com/holisticon/flynn-book-scanner/releases/download/v1.3.1/Flynn.apk)

**Comment by hypery2k** [comment]
should be available within the next hours via GooglePlay
