### ISSUE TITLE
Handling book amount

### ISSUE THREAD

**Issue by zambrovski** [holisticon/flynn-book-scanner#75]
Here is a scenario: I borrowed a book sometime and now want to add it to the corporate library. I scan the book and get the message that the book is already scanned. I could increase the amount buy one if I could be sure that the book I borrowed has not been scanned before. So actually I need a confidence that all book instances are returned, count them and correct the amount. This is reasonable, but very impractical.

I would purpose to mark scanned books. E.g by putting a scanned sign inside the book. This approach has limitations too - imagine you are validating the amount of books 4 years later. How do you recognize already rescanned books?

I think we need an approach to deal with this along with the app....

**Comment by hypery2k** [comment]
we're already discussed the marking of books and dropped this approach in the first. But let's discuss the next week on friday ...

**Comment by hypery2k** [comment]
one idea could be, that we made it possible besides the "multi-edit" mode to support editing of single book entries. The books itself are already saved separately. So if you save a book with a amount of 3 in the app it saves 3 books. So we "just" need a somekind of advanced editing mode I think

**Comment by zambrovski** [comment]
Yes. I think a kind of instance editing is a good idea. The question is how to distinguish the instances. We could just introduce a simple counter... Any chance to ask a real librarian how they solve this problem?

Simon Zambrovski
Dipl.-Ing.-Inf. 

Mobile: +49 176 1616 9010
E-Mail: simon@zambrovski.org
Internet: http://simon.zambrovski.org/
