### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by hypery2k** [holisticon/flynn-book-scanner#89]
Improve performance especially on Android

**Comment by hypery2k** [comment]
Update to cordova Android 4.0

http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html

**Comment by hypery2k** [comment]
@kxepal: You can try the latest release from the PlayStore: The performance was increased, see https://github.com/holisticon/flynn-book-scanner/releases/tag/v1.6.1

**Comment by hypery2k** [comment]
Will add pouchdb-find to improve performance furthermore: http://nolanlawson.github.io/pouchdb-find/

**Comment by kxepal** [comment]
@hypery2k thanks for the update! 1.6.1 isn't yet available for me in PlayStore, but I'll try it as soon as it will be available there.
