### ISSUE TITLE
Unable to enter server address with 9 char in the url

### ISSUE THREAD

**Issue by kxepal** [holisticon/flynn-book-scanner#90]
Steps to reproduce:
1. Install flynn book scanner
2. Open settings, enable CouchDB sync
3. Enter URL like `http://192.168.3.14`

Device: Nexus One

**Comment by hypery2k** [comment]
so you're not able to save your settings or which error you're getting? Did you use authentication?

**Comment by kxepal** [comment]
I'm not able to enter server url with 9 char in IP address (:

**Comment by kxepal** [comment]
It may be device specific bug, since it's all fine for Nexus 7 for me. The behaviour is that I tap on 9 key on keyboard, it feedbacks me that all ok, but nothing shows on input field.

**Comment by hypery2k** [comment]
Maybe an android issue. With iOS it works. I'll check it on a android device later. Which version of android you're running?

**Comment by kxepal** [comment]
2.3.7, cyanogenmod 7

**Comment by hypery2k** [comment]
Are you using a build from the github sources or from the releases APK or from play store?
Which version are you using?

**Comment by kxepal** [comment]
Release one from Google Play. 1.5.0 it says.

**Comment by kxepal** [comment]
Tested a little bit more. It seems I cannot enter only `9` and `(` characters in any fields: server url, user, password and owner. Also it doesn't allows to enter non-english characters for these fields as well.

**Comment by kxepal** [comment]
And again, these are not an issue for Nexus 7 with Android 5.1 for the same Flynn version.

**Comment by hypery2k** [comment]
tried with 2.3 emulator, but could not reproduce this error. Sorry to say but we're targeting Android 4+
But I' will update the keyboard plugin to check if that helps

**Comment by kxepal** [comment]
No problem with not supporting platform which is 3 or 4 years old if I'm right. Cannot change my phone just because it works fine (:
Do you have nightly builds anywhere to test?

**Comment by hypery2k** [comment]
you use the latest alpha tag: https://github.com/holisticon/flynn-book-scanner/releases/tag/v1.5.1

**Comment by kxepal** [comment]
@hypery2k suddenly, it didn't helped. But thanks anyway! I think I can workaround these issues (scan with the phone, type on the pad) and may be at one free rainy day will try to debug this problem. Because, well, I can understand that input of cyrillic characters may be blocked, but why `9`? That's very strange.

Since you don't have a target of supporting 2.3.x dinosaurs and if you don't have any ideas about how to fix the problem (changing android default keyboard on something else I'd already tried - same effect) feel free to close this issue. Hope it won't show itself on modern devices as well.

Thanks for your application! This is the one I dreamed about, regardless that performance issue is a true (:

**Comment by hypery2k** [comment]
especially on android 2.3 I'll agree with the performance issue.

BTW: You can dry instead of direct typing the URL using the app link:

flynnapp://config?profile=true&owner= Alexander&dbName=flynnDB_default&remotesync=true&couchdb=http%3A%2F%2F192.168.3.14

**Comment by hypery2k** [comment]
try with this build: https://github.com/holisticon/flynn-book-scanner/releases/tag/v1.5.1

**Comment by kxepal** [comment]
@hypery2k this trick works! The awesome thing that I could QR it to easily share same configuration between different devices. Thank you!
